export const GET_PROFILE_POST = "GET_PROFILE_POST";
export const GET_TIMELINE_POST = "GET_TIMELINE_POST";
export const UPLOAD_POST_FILE = "UPLOAD_POST_FILE";
export const CREATE_POST = "CREATE_POST";
export const LIKE_A_POST = "LIKE_A_POST";
